[package]
name = "rusty-machine-toy"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
rusty-machine = "^0.5.1"
rand = "^0.3.14"
rustc-serialize = "*"
csv = "*"
itertools = "*"
rustplotlib = { git = "https://github.com/ubnt-intrepid/rustplotlib.git" }
